import re
import os

with open(r"c:\Users\Voriganti\Downloads\assistant\nova_runtime\core\command_router.py", "r", encoding="utf-8") as f:
    content = f.read()

new_content = """import re
import os
from datetime import datetime, timedelta
from config.settings import JARVIS_OUTPUT_DIR
from ai.document_writer import save_as_docx, save_as_xlsx, save_as_text, save_as_code
from security.ai_guard import AIGuard

from skills.time_skill import handle_time
from skills.web_skill import handle_web
from skills.app_skill import handle_app
from skills.screenshot_skill import handle_screenshot
from skills.clipboard_skill import handle_clipboard
from skills.task_skill import handle_task
from productivity.briefing import MorningBriefing
from analytics.report_generator import ReportGenerator

from core.command_result import CommandResult

WORD_TO_NUM = {
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
    "eleven": 11, "twelve": 12, "fifteen": 15, "twenty": 20,
    "thirty": 30, "forty": 40, "fifty": 50, "sixty": 60,
    "a": 1, "an": 1
}

# Globals initialized strictly by main
_db = None
_timer_manager = None
_timer_callback = None
_personal_memory = None
_session_memory = None
    
# AI Components
_ai_engine = None
_ai_router = None
_prompt_builder = None
_last_ai_output = "" # Store the last text generated by AI
_focus_manager = None
_session_tracker = None
_analytics_tracker = None

def init_router(db, timer_manager, timer_callback, personal_memory, session_memory,
                ai_engine=None, ai_router=None, prompt_builder=None, focus_manager=None, session_tracker=None, analytics_tracker=None):
    global _db, _timer_manager, _timer_callback
    global _personal_memory, _session_memory
    global _ai_engine, _ai_router, _prompt_builder
    global _focus_manager, _session_tracker, _analytics_tracker
    _db = db
    _timer_manager = timer_manager
    _timer_callback = timer_callback
    _personal_memory = personal_memory
    _session_memory = session_memory
    _ai_engine = ai_engine
    _ai_router = ai_router
    _prompt_builder = prompt_builder
    _focus_manager = focus_manager
    _session_tracker = session_tracker
    _analytics_tracker = analytics_tracker

def route_command(command: str) -> CommandResult:
    global _last_ai_output
    lower = command.lower()

    def _log(cat, succ):
        if _analytics_tracker:
            _analytics_tracker.log_command(command, cat, succ)

    if "show analytics" in lower or "productivity report" in lower or "performance stats" in lower:
        cat = "analytics"
        if _analytics_tracker:
            report = ReportGenerator.generate_report(_analytics_tracker)
            _log(cat, True)
            return CommandResult.success(report, cat)
        _log(cat, False)
        return CommandResult.failure("Analytics tracker not initialized.", cat)

    if _focus_manager and _focus_manager.is_active():
        if _focus_manager.is_blocked(command):
            cat = "focus"
            _log(cat, False)
            return CommandResult.failure("Blocked by focus mode.", cat)
            
        ai_triggers = ["draft", "research", "explain", "plan", "notes",
                       "write", "compose", "analyze", "summarize", "describe",
                       "what is", "what are", "how does", "how do",
                       "tell me about", "create notes", "make notes",
                       "look up", "look into", "investigate", "code", "program"]
                       
        if any(t in lower for t in ai_triggers):
            allowed_ai = ["plan", "task", "notes", "explain"]
            if not any(a in lower for a in allowed_ai):
                cat = "focus"
                _log(cat, False)
                return CommandResult.failure("Blocked by focus mode.", cat)

    if ("good morning" in lower or "morning briefing" in lower or
        "what's on my plate today" in lower or "whats on my plate" in lower):
        cat = "productivity"
        if _db and _focus_manager:
            res = MorningBriefing.generate(_db, _focus_manager)
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("System components not initialized for briefing.", cat)

    focus_match = re.search(r"focus for (\d+) minutes?", lower)
    if focus_match:
        cat = "focus"
        minutes = int(focus_match.group(1))
        if _focus_manager:
            res = _focus_manager.enable(duration_minutes=minutes)
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Focus manager not initialized.", cat)

    if "enter focus mode" in lower:
        cat = "focus"
        if _focus_manager:
            res = _focus_manager.enable()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Focus manager not initialized.", cat)

    if "exit focus mode" in lower:
        cat = "focus"
        if _focus_manager:
            res = _focus_manager.disable()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Focus manager not initialized.", cat)

    if "start work session" in lower:
        cat = "productivity"
        if _session_tracker:
            res = _session_tracker.start_session()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Session tracker not initialized.", cat)

    if "end work session" in lower:
        cat = "productivity"
        if _session_tracker:
            res = _session_tracker.end_session()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Session tracker not initialized.", cat)

    if "how long have i worked" in lower:
        cat = "productivity"
        if _session_tracker:
            total = _session_tracker.get_today_total_minutes()
            res = f"You have worked for {total:.1f} minutes today."
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Session tracker not initialized.", cat)

    if "time" in lower or "date" in lower or "day" in lower or "year" in lower:
        cat = "system"
        if not any(k in lower for k in ["timer", "remind", "plan", "draft", "research", "notes", "analyze"]):
            res = handle_time(command)
            _log(cat, True)
            return CommandResult.success(res, cat)

    if "set timer" in lower or "timer for" in lower:
        cat = "reminder"
        if not _timer_manager:
            _log(cat, False)
            return CommandResult.failure("Timer manager not initialized.", cat)
        match = re.search(r'(\d+)\s*minute', lower)
        if match:
            minutes = int(match.group(1))
            res = _timer_manager.set_timer(minutes * 60, _timer_callback)
            msg = f"Timer set for {minutes} minute(s)."
            _log(cat, True)
            return CommandResult.success(msg, cat)
        _log(cat, False)
        return CommandResult.failure("Please specify the number of minutes for the timer.", cat)
    
    if "check timer" in lower or "how much time" in lower or "timer status" in lower:
        cat = "reminder"
        if not _timer_manager:
            _log(cat, False)
            return CommandResult.failure("Timer manager not initialized.", cat)
        remaining = _timer_manager.get_remaining_time()
        if remaining <= 0:
            _log(cat, True)
            return CommandResult.success("There is no active timer.", cat)
        m = int(remaining // 60)
        s = int(remaining % 60)
        if m > 0:
            msg = f"Timer has {m} minutes and {s} seconds remaining."
        else:
            msg = f"Timer has {s} seconds remaining."
        _log(cat, True)
        return CommandResult.success(msg, cat)
    
    if "cancel timer" in lower or "stop timer" in lower:
        cat = "reminder"
        if not _timer_manager:
            _log(cat, False)
            return CommandResult.failure("Timer manager not initialized.", cat)
        if _timer_manager.cancel_timer():
            _log(cat, True)
            return CommandResult.success("Timer cancelled.", cat)
        _log(cat, True)
        return CommandResult.success("No active timer to cancel.", cat)

    if "remind me in" in lower and "to" in lower:
        cat = "reminder"
        match = re.search(r'remind me in (\d+)\s*minutes? to (.*)', lower)
        if match and _db:
            minutes = int(match.group(1))
            message = match.group(2).strip()
            remind_time = (datetime.now() + timedelta(minutes=minutes)).strftime("%Y-%m-%d %H:%M:%S")
            _db.add_reminder(message, remind_time)
            msg = f"Reminder set for {minutes} minute(s) from now."
            _log(cat, True)
            return CommandResult.success(msg, cat)

    if re.search(r'\b(open|launch|start)\b', lower) or "search" in lower or "go to" in lower:
        cat = "system"
        if any(k in lower for k in ["timer", "remind", "plan", "draft", "research", "notes", "analyze", "browser"]):
            pass  # Let AI or explicitly assigned handlers take it
        elif "search" in lower or "website" in lower or "go to" in lower or ".com" in lower or ".org" in lower:
            res = handle_web(command)
            _log(cat, True)
            return CommandResult.success(res, cat)
        elif "app" in lower or "launch" in lower or "start" in lower:
            res = handle_app(command)
            succ = "Failed to open" not in res and "Unknown application" not in res
            _log(cat, succ)
            if succ:
                return CommandResult.success(res, cat)
            else:
                return CommandResult.failure(res, cat)
        else:
            web_targets = ["youtube", "google", "chat gpt", "chatgpt", "github", "gmail", "facebook", "twitter", "netflix"]
            if any(w in lower for w in web_targets):
                res = handle_web(command)
                _log(cat, True)
                return CommandResult.success(res, cat)
            else:
                res = handle_app(command)
                succ = "Failed to open" not in res and "Unknown application" not in res
                _log(cat, succ)
                if succ:
                    return CommandResult.success(res, cat)
                else:
                    return CommandResult.failure(res, cat)

    if "screenshot" in lower:
        cat = "system"
        res = handle_screenshot(command)
        _log(cat, True)
        return CommandResult.success(res, cat)

    if "clipboard" in lower or "copy" in lower or "paste" in lower:
        cat = "system"
        res = handle_clipboard(command)
        _log(cat, True)
        return CommandResult.success(res, cat)
        
    if "add task" in lower or "new task" in lower or "remind me to" in lower:
        cat = "task"
        res = handle_task(command, _db)
        _log(cat, True)
        return CommandResult.success(res, cat)
        
    if "list tasks" in lower or "show tasks" in lower or "what are my tasks" in lower:
        cat = "task"
        res = handle_task(command, _db)
        _log(cat, True)
        return CommandResult.success(res, cat)
        
    if "complete task" in lower or "finish task" in lower:
        cat = "task"
        res = handle_task(command, _db)
        succ = "not found" not in res.lower() and "specify" not in res.lower()
        _log(cat, succ)
        if succ:
            return CommandResult.success(res, cat)
        return CommandResult.failure(res, cat)
        
    if "delete task" in lower or "remove task" in lower:
        cat = "task"
        res = handle_task(command, _db)
        succ = "not found" not in res.lower() and "specify" not in res.lower()
        _log(cat, succ)
        if succ:
            return CommandResult.success(res, cat)
        return CommandResult.failure(res, cat)
        
    if "what was i doing" in lower or "last task" in lower:
        cat = "task"
        res = handle_task(command, _db)
        _log(cat, True)
        return CommandResult.success(res, cat)

    # --- Memory commands ---
    if _personal_memory:
        cat = "productivity"
        if "remember that" in lower or "remember this" in lower:
            res = _personal_memory.add_memory(command)
            _log(cat, True)
            return CommandResult.success(res, cat)
            
        if "what do you remember" in lower or "list memories" in lower or "list memory" in lower:
            res = _personal_memory.list_memories()
            _log(cat, True)
            return CommandResult.success(res, cat)
            
        if "delete memory" in lower:
            match = re.search(r"delete memory\s*(\d+)", lower)
            if match:
                memory_id = int(match.group(1))
                res = _personal_memory.delete_memory(memory_id)
                succ = "deleted" in res.lower()
                _log(cat, succ)
                if succ:
                    return CommandResult.success(res, cat)
                return CommandResult.failure(res, cat)
            _log(cat, False)
            return CommandResult.failure("Which memory ID should I delete?", cat)

    if lower.strip() in ["confirm", "yes", "proceed"] and _session_memory:
        cat = "ai"
        pending = getattr(_session_memory, "pending_file", None)
        if pending:
            # We had a pending file action requiring confirmation
            filename = pending["filename"]
            content = pending["content"]
            title = pending["title"]
            filepath = pending["filepath"]
            format_ext = pending["format_ext"]

            _session_memory.update(command, "File confirmed.")
            # Clear pending
            _session_memory.pending_file = None

            if format_ext == ".xlsx":
                try:
                    save_as_xlsx(content, filepath, title=title)
                except Exception:
                    save_as_docx(content, filepath.replace(".xlsx", ".docx"), title=title)
                    filename = filename.replace(".xlsx", ".docx")
            elif format_ext == ".docx":
                save_as_docx(content, filepath, title=title)
            elif format_ext == ".txt":
                save_as_text(content, filepath)
            else:
                save_as_code(content, filepath)
                
            msg = f"Action confirmed. {filename} saved on your Desktop."
            _log(cat, True)
            return CommandResult.success(msg, cat)

    ai_triggers = ["draft", "research", "explain", "plan", "notes",
                   "write", "compose", "analyze", "summarize", "describe",
                   "what is", "what are", "how does", "how do",
                   "tell me about", "create notes", "make notes",
                   "look up", "look into", "investigate", "code", "program"]

    # --- Conversational Flow ("more", "save it", "yes") ---
    if lower.strip() in ["yes", "yeah", "yep", "sure", "do it", "please do"]:
        cat = "ai"
        if _session_memory and _session_memory.get_last().get("last_response"):
            last_resp = _session_memory.get_last().get("last_response")
            # Check if Jarvis just asked to create a document
            if "Would you like me to create a full document on this" in last_resp:
                last_cmd = _session_memory.get_last().get("last_command", "")
                # Rewrite command to trigger the document generator
                command = "draft document on " + last_cmd
                lower = command.lower()
                print("[AI] User confirmed document creation.")
                # Fall through to the main AI handler below

    if "more" == lower.strip() or "tell me more" in lower or "explain more" in lower:
        cat = "ai"
        if _session_memory and _session_memory.get_last().get("last_command"):
            last_cmd = _session_memory.get_last().get("last_command")
            # Ensure the last command was an AI question
            if any(t in last_cmd.lower() for t in ai_triggers):
                print("[AI] Generating response (more detail)...")
                memories = _personal_memory._memories if _personal_memory else []
                prompt = _prompt_builder.build("explain", last_cmd, memories, detail_level="long")
                # Tell me more
                result = _ai_engine.generate(prompt)
                
                if _analytics_tracker:
                    _analytics_tracker.log_ai_call(result.get("success", False))

                if not result.get("success", False):
                    err = result.get("error", "AI request failed.")
                    _log(cat, False)
                    return CommandResult.failure(err, cat)
                
                ai_output = result.get("content", "")
                _last_ai_output = ai_output
                _session_memory.update(command, ai_output)
                _log(cat, True)
                return CommandResult.success(ai_output, cat)
        _log(cat, False)
        return CommandResult.failure("I don't have enough context to explain more. Please ask a specific question.", cat)

    if lower.strip() in ["save it", "save that", "create document"]:
        cat = "ai"
        if not _last_ai_output:
            _log(cat, False)
            return CommandResult.failure("There is no recent output to save.", cat)
        
        if not os.path.exists(JARVIS_OUTPUT_DIR):
            os.makedirs(JARVIS_OUTPUT_DIR)
            
        topic = "saved_output"
        if _session_memory and _session_memory.get_last().get("last_command"):
            topic = AIGuard.sanitize_filename(_session_memory.get_last().get("last_command"))
        
        filename = topic + ".docx"
        filepath = os.path.join(JARVIS_OUTPUT_DIR, filename)
        save_as_docx(_last_ai_output, filepath, title=topic.replace("_", " ").title())
        msg = "Content saved as " + filename + " on your Desktop."
        _log(cat, True)
        return CommandResult.success(msg, cat)

    # --- Save last AI output (custom name) ---
    if lower.startswith("save as "):
        cat = "ai"
        filename = command[8:].strip()
        if not filename:
            _log(cat, False)
            return CommandResult.failure("Please specify a filename.", cat)
        # Prevent Path Traversal by extracting just the basename
        filename = os.path.basename(filename)
        if not filename.endswith(".txt"):
            filename += ".txt"
        if not os.path.exists(JARVIS_OUTPUT_DIR):
            os.makedirs(JARVIS_OUTPUT_DIR)
        filepath = os.path.join(JARVIS_OUTPUT_DIR, filename)
        if not _last_ai_output:
            _log(cat, False)
            return CommandResult.failure("No AI output to save.", cat)
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(_last_ai_output)
            _log(cat, True)
            return CommandResult.success("Saved to " + filepath, cat)
        except Exception as e:
            _log(cat, False)
            return CommandResult.failure("Error saving file: " + str(e), cat)

    # --- AI commands ---
    # Task types that produce documents (auto-save to file)
    _document_tasks = {"draft", "research", "plan", "notes"}
    
    if _ai_engine and any(trigger in lower for trigger in ai_triggers):
        cat = "ai"
        try:
            task_type = _ai_router.route(command) if _ai_router else "explain"
            memories = []
            if _personal_memory:
                memories = _personal_memory._memories
            
            # Determine detail level for 'explain'
            detail_level = "short"  # Default to 2-3 sentences max

            prompt = _prompt_builder.build(task_type, command, memories, detail_level) if _prompt_builder else command
            print(f"[AI] Generating response ({task_type})...")
            result = _ai_engine.generate(prompt)

            if _analytics_tracker:
                _analytics_tracker.log_ai_call(result.get("success", False))
            
            if not result.get("success", False):
                err = result.get("error", "AI request failed.")
                _log(cat, False)
                return CommandResult.failure(err, cat)
                
            ai_output = result.get("content", "")
            _last_ai_output = ai_output
            
            if _session_memory:
                _session_memory.update(command, ai_output)

            # Output logic based on target format
            format_ext = _ai_router.get_format(task_type, command) if _ai_router else ".docx"
            
            if task_type in ["draft", "research", "plan", "analyze", "notes", "code"]:
                if not os.path.exists(JARVIS_OUTPUT_DIR):
                    os.makedirs(JARVIS_OUTPUT_DIR)
                
                # Generate base filename
                safe_name = AIGuard.sanitize_filename(lower)
                if not safe_name:
                    safe_name = task_type + "_output"
                title = safe_name.replace("_", " ").title()
                
                filename = safe_name + format_ext
                filepath = os.path.join(JARVIS_OUTPUT_DIR, filename)

                if AIGuard.requires_confirmation(filename):
                    if _session_memory:
                        # Store pending action
                        _session_memory.update(command, "Pending confirmation for " + filename)
                        _session_memory.pending_file = {
                            "filename": filename,
                            "content": ai_output,
                            "title": title,
                            "filepath": filepath,
                            "format_ext": format_ext
                        }
                    msg = f"Safety check: Generating {filename} requires confirmation. Say 'confirm' to proceed."
                    _log(cat, True)
                    return CommandResult.success(msg, cat) # Returns success because it successfully intercepted

                if format_ext == ".xlsx":
                    try:
                        save_as_xlsx(ai_output, filepath, title=title)
                    except Exception:
                        save_as_docx(ai_output, filepath.replace(".xlsx", ".docx"), title=title)
                        filename = filename.replace(".xlsx", ".docx")
                elif format_ext == ".docx":
                    save_as_docx(ai_output, filepath, title=title)
                elif format_ext == ".txt":
                    save_as_text(ai_output, filepath)
                else: # code files (.py, .js, etc)
                    save_as_code(ai_output, filepath)

                _log(cat, True)
                return CommandResult.success(f"Document generated successfully.", cat)
            else:
                # Conversational responses (explain)
                if not AIGuard.should_speak_full_output(ai_output):
                    _log(cat, True)
                    return CommandResult.success("Document generated successfully.", cat)
                _log(cat, True)
                return CommandResult.success(ai_output, cat)
        except Exception as e:
            _log(cat, False)
            return CommandResult.failure("AI processing error: " + str(e), cat)

    cat = "system"
    _log(cat, False)
    return CommandResult.failure("I did not understand the command.", cat)
"""

with open(r"c:\Users\Voriganti\Downloads\assistant\nova_runtime\core\command_router.py", "w", encoding="utf-8") as f:
    f.write(new_content)
