from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from jarvis.core.agent_registry import AgentRegistry
from jarvis.core.planner import Planner
from jarvis.core.router import JarvisRouter
from jarvis.execution.executor import Executor
from jarvis.nlp.segment_parser import split_segments


class Orchestrator:
    def __init__(
        self,
        planner: Planner,
        agent_registry: AgentRegistry,
        executor: Executor | None = None,
        router: JarvisRouter | None = None,
    ) -> None:
        # The orchestrator coordinates planning and execution only.
        # It does not implement tool behavior or agent-specific actions.
        self.planner = planner
        self.agent_registry = agent_registry
        self.executor = executor or Executor(registry=agent_registry)
        self.router = router or JarvisRouter()

    async def orchestrate(
        self,
        parsed_command: dict[str, Any],
        context: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Central coordination flow:
        parsed_command -> planner.create_plan -> executor.execute -> collected results.
        """
        execution_context = self._build_execution_context(parsed_command, context)
        task_graph = self.planner.create_plan(parsed_command)

        # Timeline of execution updates generated by the executor.
        execution_events: list[dict[str, Any]] = []

        def _monitor(event: dict[str, Any]) -> None:
            execution_events.append(
                {
                    **event,
                    "timestamp": datetime.now(UTC).isoformat(),
                }
            )

        results = await self.executor.execute(
            task_graph,
            context=execution_context,
        )
        for task_result in results.values():
            _monitor(task_result)

        summary = self._summarize_results(results)
        return {
            "parsed_command": parsed_command,
            "context": execution_context,
            "task_graph": task_graph,
            "execution_events": execution_events,
            "results": results,
            "summary": summary,
        }

    async def handle_command(self, command: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
        """Backward-compatible helper for raw command callers."""
        normalized = " ".join(str(command).strip().split())
        segments = split_segments(normalized)
        parsed_command: dict[str, Any] = {
            "text": normalized,
            "segments": segments,
            "source": "raw",
        }
        try:
            routed = await self.router.route(parsed_command)
            actions = routed.get("actions", [])
            if isinstance(actions, list):
                parsed_command["actions"] = actions
            parsed_command["provider"] = routed.get("provider", "deterministic")
            if not parsed_command.get("actions"):
                parsed_command["actions"] = [{"intent": "legacy_command", "params": {"text": normalized}}]
        except Exception:
            # Keep command handling resilient if router dependencies are unavailable.
            parsed_command["actions"] = [{"intent": "legacy_command", "params": {"text": normalized}}]
            parsed_command.setdefault("provider", "deterministic")
        return await self.orchestrate(parsed_command, context=context)

    def _build_execution_context(
        self, parsed_command: dict[str, Any], context: dict[str, Any] | None
    ) -> dict[str, Any]:
        base_context = dict(context or {})
        base_context.setdefault("session_id", "default")
        base_context["command_text"] = parsed_command.get("text", "")
        base_context["received_at"] = datetime.now(UTC).isoformat()
        return base_context

    def _summarize_results(self, results: dict[str, Any]) -> dict[str, int]:
        total = len(results)
        success = sum(1 for result in results.values() if result.get("status") in {"done", "complete"})
        failed = total - success
        return {"total_tasks": total, "successful_tasks": success, "failed_tasks": failed}
