import re
import os
import time
from datetime import datetime, timedelta
from config.settings import JARVIS_OUTPUT_DIR
from ai.document_writer import save_as_docx, save_as_xlsx, save_as_text, save_as_code
from security.ai_guard import AIGuard

from skills.time_skill import handle_time
from skills.web_skill import handle_web
from skills.app_skill import handle_app
from skills.screenshot_skill import handle_screenshot
from skills.clipboard_skill import handle_clipboard
from skills.task_skill import handle_task
from productivity.briefing import MorningBriefing
from analytics.report_generator import ReportGenerator

from core.command_result import CommandResult
from deployment.autostart import enable_autostart, disable_autostart

from core.segment_parser import split_segments
from core.entity_resolver import resolve_entity
from core.entity_registry import EntityRegistry
from skills.macro_skill import create_macro, delete_macro, list_macros, get_macro
from nlu.intent_classifier import IntentClassifier

_start_time = time.time()
try:
    import psutil
except ImportError:
    psutil = None

WORD_TO_NUM = {
    "one": 1, "two": 2, "three": 3, "four": 4, "five": 5,
    "six": 6, "seven": 7, "eight": 8, "nine": 9, "ten": 10,
    "eleven": 11, "twelve": 12, "fifteen": 15, "twenty": 20,
    "thirty": 30, "forty": 40, "fifty": 50, "sixty": 60,
    "a": 1, "an": 1
}

# Globals initialized strictly by main
_db = None
_timer_manager = None
_timer_callback = None
_personal_memory = None
_session_memory = None
    
# AI Components
_ai_engine = None
_ai_router = None
_prompt_builder = None
_last_ai_output = "" # Store the last text generated by AI
_focus_manager = None
_session_tracker = None
_analytics_tracker = None
_entity_registry = EntityRegistry()
_intent_classifier = IntentClassifier()

def init_router(db, timer_manager, timer_callback, personal_memory, session_memory,
                ai_engine=None, ai_router=None, prompt_builder=None, focus_manager=None, session_tracker=None, analytics_tracker=None):
    global _db, _timer_manager, _timer_callback
    global _personal_memory, _session_memory
    global _ai_engine, _ai_router, _prompt_builder
    global _focus_manager, _session_tracker, _analytics_tracker
    _db = db
    _timer_manager = timer_manager
    _timer_callback = timer_callback
    _personal_memory = personal_memory
    _session_memory = session_memory
    _ai_engine = ai_engine
    _ai_router = ai_router
    _prompt_builder = prompt_builder
    _focus_manager = focus_manager
    _session_tracker = session_tracker
    _analytics_tracker = analytics_tracker

def route_command(command: str) -> CommandResult:
    lower_cmd = command.lower().strip()
    
    if lower_cmd.startswith("create macro"):
        cat = "system"
        pattern = r'^create macro (.+?)\b(open|launch|start|search|go to|set timer|cancel timer|check timer|remind me|add task|list tasks|show tasks|complete task|finish task|delete task|remove task|enter focus mode|exit focus mode|start work session|end work session)(.*)'
        match = re.search(pattern, lower_cmd)
        
        if not match:
            return CommandResult.failure("Format: create macro <name> <actions>", cat)
            
        name = match.group(1).strip()
        actions_str = match.group(2) + match.group(3)
        actions = split_segments(actions_str)
        res = create_macro(_db, name, actions)
        
        if _analytics_tracker:
            _analytics_tracker.log_command(command, cat, "created" in res)
            
        if "created" in res:
            return CommandResult.success(res, cat)
        return CommandResult.failure(res, cat)
        
    if lower_cmd.startswith("delete macro"):
        cat = "system"
        name = lower_cmd[12:].strip()
        res = delete_macro(_db, name)
        
        if _analytics_tracker:
            _analytics_tracker.log_command(command, cat, "deleted" in res)
            
        if "deleted" in res:
            return CommandResult.success(res, cat)
        return CommandResult.failure(res, cat)
        
    if lower_cmd == "list macros":
        cat = "system"
        res = list_macros(_db)
        
        if _analytics_tracker:
            _analytics_tracker.log_command(command, cat, True)
            
        return CommandResult.success(res, cat)
        
    segments = split_segments(command)
    
    # Expand macros
    expanded_segments = []
    
    if _db:
        known_macros = [m['name'] for m in _db.list_macros()]
    else:
        known_macros = []
        
    for seg in segments:
        seg_lower = seg.lower().strip()
        
        # Prevent parsing macro management commands themselves into macro expansions
        if seg_lower.startswith("create macro") or seg_lower.startswith("delete macro") or seg_lower == "list macros":
            expanded_segments.append(seg)
            continue
            
        matched_macro = None
        
        if known_macros:
            entity, conf = resolve_entity(seg_lower, known_macros)
            # Find fuzzy match with 0.8 cutoff and unique best match requirement
            if conf >= 0.8:
                matched_macro = entity
                
        if matched_macro and _db:
            actions = get_macro(_db, matched_macro)
            if actions:
                expanded_segments.extend(actions)
            else:
                expanded_segments.append(seg)
        else:
            expanded_segments.append(seg)
            
    segments = expanded_segments
    expanded = len(segments) > len(split_segments(command)) or (len(segments) == 1 and segments[0] != command)

    if len(segments) <= 1 and not expanded:
        return _route_single_command(command)
        
    known_verbs = [
        "open ", "launch ", "start ", "search ", "go to ",
        "set timer", "cancel timer", "check timer", "remind me",
        "add task", "list tasks", "show tasks", "complete task", "finish task", "delete task", "remove task",
        "enter focus mode", "exit focus mode", "start work session", "end work session"
    ]
    
    resolved_segments = []
    unresolved_segments = []
    
    for seg in segments:
        seg_lower = seg.lower()
        matched = False
        
        # Check if the segment starts with a non-entity-requiring verb
        verbs_without_entities = [
            "set timer", "cancel timer", "check timer", "remind me",
            "add task", "list tasks", "show tasks", "complete task", "finish task", "delete task", "remove task",
            "enter focus mode", "exit focus mode", "start work session", "end work session"
        ]
        
        for v in verbs_without_entities:
            if seg_lower.startswith(v):
                resolved_segments.append(seg)
                matched = True
                break
                
        if matched:
            continue
            
        verb = None
        for v in ["open ", "launch ", "start ", "search ", "go to "]:
            if seg_lower.startswith(v):
                verb = v.strip()
                break
                
        if verb:
            entity_token = seg_lower[len(verb):].strip()
            if entity_token:
                res = _entity_registry.resolve(entity_token)
                if res:
                    _, canonical = res
                    resolved_segments.append(f"{verb} {canonical}")
                else:
                    unresolved_segments.append(seg)
            else:
                resolved_segments.append(seg)
        else:
            res = _entity_registry.resolve(seg_lower)
            if res:
                _, canonical = res
                resolved_segments.append(f"open {canonical}")
            else:
                unresolved_segments.append(seg)
                
    if resolved_segments:
        results = []
        for r_seg in resolved_segments:
            res = _route_single_command(r_seg)
            results.append(res.message)
            
        combined_msg = "\n".join(results)
        
        final_unresolved = []
        for u_seg in unresolved_segments:
            intent, conf = _intent_classifier.classify(u_seg)
            if conf >= 0.7 and intent:
                res = _route_single_command(u_seg, bypass_strict_validation=True, predicted_intent=intent)
                combined_msg += "\n" + res.message
            else:
                final_unresolved.append(u_seg)
        unresolved_segments = final_unresolved
        
        if len(unresolved_segments) == len(segments):
            if expanded:
                # If nothing resolved but it's an expanded macro, evaluate them all directly 
                # rather than falling back to the original macro string which will fail
                results = []
                for u_seg in segments:
                    intent, conf = _intent_classifier.classify(u_seg)
                    res = _route_single_command(u_seg, bypass_strict_validation=True, predicted_intent=intent if conf >= 0.7 else None)
                    results.append(res.message)
                return CommandResult.success("\n".join(results), "system")
            intent, conf = _intent_classifier.classify(command)
            return _route_single_command(command, predicted_intent=intent if conf >= 0.7 else None)
        elif unresolved_segments:
            if expanded:
                for u_seg in unresolved_segments:
                    intent, conf = _intent_classifier.classify(u_seg)
                    res = _route_single_command(u_seg, bypass_strict_validation=True, predicted_intent=intent if conf >= 0.7 else None)
                    combined_msg += "\n" + res.message
                
            else:
                # if there is a single segment command that failed entity validation
                if len(segments) == 1:
                    intent, conf = _intent_classifier.classify(command)
                    return _route_single_command(command, predicted_intent=intent if conf >= 0.7 else None)
                combined_msg += f"\n(Unresolved: {', '.join(unresolved_segments)})"
        return CommandResult.success(combined_msg, "system")
    
    if expanded:
        results = []
        for seg in segments:
            intent, conf = _intent_classifier.classify(seg)
            res = _route_single_command(seg, bypass_strict_validation=True, predicted_intent=intent if conf >= 0.7 else None)
            results.append(res.message)
        return CommandResult.success("\n".join(results), "system")
        
    intent, conf = _intent_classifier.classify(command)
    return _route_single_command(command, predicted_intent=intent if conf >= 0.7 else None)

def _route_single_command(command: str, bypass_strict_validation: bool = False, predicted_intent: str = None) -> CommandResult:
    global _last_ai_output
    lower = command.lower()

    def _log(cat, succ):
        if _analytics_tracker:
            _analytics_tracker.log_command(command, cat, succ)

    if "enable auto start" in lower:
        cat = "system"
        success, msg = enable_autostart()
        _log(cat, success)
        if success:
            return CommandResult.success(msg, cat)
        return CommandResult.failure(msg, cat)

    if "disable auto start" in lower:
        cat = "system"
        success, msg = disable_autostart()
        _log(cat, success)
        if success:
            return CommandResult.success(msg, cat)
        return CommandResult.failure(msg, cat)

    if "health check" in lower or predicted_intent == "health":
        cat = "system"
        uptime_seconds = int(time.time() - _start_time)
        uptime_str = str(timedelta(seconds=uptime_seconds))
        
        focus_state = "Active" if _focus_manager and _focus_manager.is_active() else "Inactive"
        work_session = "Active" if _session_tracker and _session_tracker.current_start else "Inactive"
        
        log_file = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "logs", "runtime.log")
        log_size_kb = os.path.getsize(log_file) / 1024 if os.path.exists(log_file) else 0
        
        mem_usage = "Unknown"
        if psutil:
            process = psutil.Process(os.getpid())
            mem_usage = f"{process.memory_info().rss / (1024 * 1024):.1f} MB"
            
        res = f"Uptime: {uptime_str}\nFocus State: {focus_state}\nWork Session: {work_session}\nLog Size: {log_size_kb:.1f} MB\nMemory Usage: {mem_usage}"
        if log_size_kb < 1:
            res = res.replace(f"Log Size: {log_size_kb:.1f} MB", f"Log Size: {log_size_kb*1024:.1f} KB")
        elif log_size_kb >= 1:
             res = res.replace(f"Log Size: {log_size_kb:.1f} MB", f"Log Size: {log_size_kb:.1f} KB") # Wait, previous was kb, I will use KB
        res = f"Uptime: {uptime_str}\nFocus State: {focus_state}\nWork Session: {work_session}\nLog Size: {log_size_kb:.1f} KB\nMemory Usage: {mem_usage}"
        _log(cat, True)
        return CommandResult.success(res, cat)

    if "show analytics" in lower or "productivity report" in lower or "performance stats" in lower or predicted_intent == "analytics":
        cat = "analytics"
        if _analytics_tracker:
            report = ReportGenerator.generate_report(_analytics_tracker)
            _log(cat, True)
            return CommandResult.success(report, cat)
        _log(cat, False)
        return CommandResult.failure("Analytics tracker not initialized.", cat)

    if _focus_manager and _focus_manager.is_active():
        if _focus_manager.is_blocked(command) and predicted_intent not in ["focus", "timer", "health", "analytics", "task"]:
            cat = "focus"
            _log(cat, False)
            return CommandResult.failure("Blocked by focus mode.", cat)
            
        ai_triggers = ["draft", "research", "explain", "plan", "notes",
                       "write", "compose", "analyze", "summarize", "describe",
                       "what is", "what are", "how does", "how do",
                       "tell me about", "create notes", "make notes",
                       "look up", "look into", "investigate", "code", "program"]
                       
        if (any(t in lower for t in ai_triggers) or predicted_intent in ["explain", "generate", "analyze", "search"]) and predicted_intent not in ["focus", "timer", "health", "analytics", "task"]:
            allowed_ai = ["plan", "task", "notes", "explain"]
            if not any(a in lower for a in allowed_ai) and predicted_intent not in allowed_ai:
                cat = "focus"
                _log(cat, False)
                return CommandResult.failure("Blocked by focus mode.", cat)

    if ("good morning" in lower or "morning briefing" in lower or
        "what's on my plate today" in lower or "whats on my plate" in lower):
        cat = "productivity"
        if _db and _focus_manager:
            res = MorningBriefing.generate(_db, _focus_manager)
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("System components not initialized for briefing.", cat)

    focus_match = re.search(r"focus for (\d+) minutes?", lower)
    if focus_match:
        cat = "focus"
        minutes = int(focus_match.group(1))
        if _focus_manager:
            res = _focus_manager.enable(duration_minutes=minutes)
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Focus manager not initialized.", cat)

    if "enter focus mode" in lower or predicted_intent == "focus":
        cat = "focus"
        if _focus_manager:
            res = _focus_manager.enable()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Focus manager not initialized.", cat)

    if "exit focus mode" in lower:
        cat = "focus"
        if _focus_manager:
            res = _focus_manager.disable()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Focus manager not initialized.", cat)

    if "start work session" in lower:
        cat = "productivity"
        if _session_tracker:
            res = _session_tracker.start_session()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Session tracker not initialized.", cat)

    if "end work session" in lower:
        cat = "productivity"
        if _session_tracker:
            res = _session_tracker.end_session()
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Session tracker not initialized.", cat)

    if "how long have i worked" in lower:
        cat = "productivity"
        if _session_tracker:
            total = _session_tracker.get_today_total_minutes()
            res = f"You have worked for {total:.1f} minutes today."
            _log(cat, True)
            return CommandResult.success(res, cat)
        _log(cat, False)
        return CommandResult.failure("Session tracker not initialized.", cat)

    if "time" in lower or "date" in lower or "day" in lower or "year" in lower:
        cat = "system"
        if not any(k in lower for k in ["timer", "remind", "plan", "draft", "research", "notes", "analyze"]):
            res = handle_time(command)
            _log(cat, True)
            return CommandResult.success(res, cat)

    if "set timer" in lower or "timer for" in lower or predicted_intent == "timer":
        cat = "reminder"
        if not _timer_manager:
            _log(cat, False)
            return CommandResult.failure("Timer manager not initialized.", cat)
        match = re.search(r'(\d+)\s*minute', lower)
        if match:
            minutes = int(match.group(1))
            res = _timer_manager.set_timer(minutes * 60, _timer_callback)
            msg = f"Timer set for {minutes} minute(s)."
            _log(cat, True)
            return CommandResult.success(msg, cat)
        
        # FastText intent extraction
        if predicted_intent == "timer":
            ext_match = re.search(r'(\d+)', lower)
            if ext_match:
                mins = int(ext_match.group(1))
                res = _timer_manager.set_timer(mins * 60, _timer_callback)
                msg = f"Timer set for {mins} minute(s)."
                _log(cat, True)
                return CommandResult.success(msg, cat)
            
        _log(cat, False)
        return CommandResult.failure("Please specify the number of minutes for the timer.", cat)
    
    if "check timer" in lower or "how much time" in lower or "timer status" in lower:
        cat = "reminder"
        if not _timer_manager:
            _log(cat, False)
            return CommandResult.failure("Timer manager not initialized.", cat)
        remaining = _timer_manager.get_remaining_time()
        if remaining <= 0:
            _log(cat, True)
            return CommandResult.success("There is no active timer.", cat)
        m = int(remaining // 60)
        s = int(remaining % 60)
        if m > 0:
            msg = f"Timer has {m} minutes and {s} seconds remaining."
        else:
            msg = f"Timer has {s} seconds remaining."
        _log(cat, True)
        return CommandResult.success(msg, cat)
    
    if "cancel timer" in lower or "stop timer" in lower:
        cat = "reminder"
        if not _timer_manager:
            _log(cat, False)
            return CommandResult.failure("Timer manager not initialized.", cat)
        if _timer_manager.cancel_timer():
            _log(cat, True)
            return CommandResult.success("Timer cancelled.", cat)
        _log(cat, True)
        return CommandResult.success("No active timer to cancel.", cat)

    if "remind me in" in lower and "to" in lower:
        cat = "reminder"
        match = re.search(r'remind me in (\d+)\s*minutes? to (.*)', lower)
        if match and _db:
            minutes = int(match.group(1))
            message = match.group(2).strip()
            remind_time = (datetime.now() + timedelta(minutes=minutes)).strftime("%Y-%m-%d %H:%M:%S")
            _db.add_reminder(message, remind_time)
            msg = f"Reminder set for {minutes} minute(s) from now."
            _log(cat, True)
            return CommandResult.success(msg, cat)

    if re.search(r'\b(open|launch|start)\b', lower) or "search" in lower or "go to" in lower:
        cat = "system"
        if any(k in lower for k in ["timer", "remind", "plan", "draft", "research", "notes", "analyze"]):
            pass  # Let AI or explicitly assigned handlers take it
        elif "search" in lower or "website" in lower or "go to" in lower or ".com" in lower or ".org" in lower:
            res = handle_web(command)
            _log(cat, True)
            return CommandResult.success(res, cat)
        else:
            # We must validate entities for web targets and local apps 
            # to respect Phase I.1 "safety rule" explicitly avoiding fuzzy execution < 0.75
            known_entities = [
                "youtube", "google", "chat gpt", "chatgpt", "github", "gmail", 
                "facebook", "twitter", "netflix", "notepad", "steam", "timer", "yt"
            ]
            
            # Extract target name
            target = command.lower()
            verb = None
            for v in ["open ", "launch ", "start "]:
                if target.startswith(v):
                    verb = v
                    target = target[len(v):].strip()
                    break
            
            if verb:
                if bypass_strict_validation:
                    return CommandResult.failure("Unknown resolved entity bypass.", "system")
                entity_token = lower[len(verb):].strip()
                if entity_token:
                    if predicted_intent:
                        # FastText correctly claimed it, skip strict matching to prevent overwrite
                        pass 
                    else:
                        res = _entity_registry.resolve(entity_token)
                        if res:
                            ent_type, target = res
                            if ent_type == "website":
                                success, act_msg = handle_web(target)
                                _log("web", success)
                                return CommandResult.success(act_msg, "web") if success else CommandResult.failure(act_msg, "web")
                            elif ent_type == "application":
                                success, act_msg = handle_app(target)
                                _log("app", success)
                                return CommandResult.success(act_msg, "app") if success else CommandResult.failure(act_msg, "app")
                            
                        _log("system", False)
                        if len(split_segments(command)) == 1:
                            # Let NLU attempt to rescue strict single entity failures
                            intent, conf = _intent_classifier.classify(command)
                            if conf >= 0.7:
                                return _route_single_command(command, bypass_strict_validation=True, predicted_intent=intent)
                        return CommandResult.failure(f"Application or website '{entity_token}' not found in registry.", "system")
            
            res = _entity_registry.resolve(target)
            
            if res:
                ent_type, canonical = res

                if ent_type == "website":
                    import webbrowser
                    try:
                        webbrowser.open(canonical)
                        msg = f"Opening {target.title()}..."
                        _log(cat, True)
                        return CommandResult.success(msg, cat)
                    except Exception as e:
                        return CommandResult.failure(f"Failed to open website '{target}'.", cat)
                elif ent_type == "application":
                    import subprocess
                    try:
                        subprocess.Popen(canonical)
                        msg = f"Opening {target.title()}..."
                        _log(cat, True)
                        return CommandResult.success(msg, cat)
                    except Exception as e:
                        return CommandResult.failure(f"Application '{target}' failed to start.", cat)
            elif bypass_strict_validation:
                # Retain original behavior perfectly for unknown bypassed expansions
                res = handle_app(f"open {target}")
                succ = "Failed to open" not in res and "Unknown application" not in res
                _log(cat, succ)
                if succ:
                    return CommandResult.success(res, cat)
                else:
                    return CommandResult.failure(res, cat)
            else:
                # Block execution for unrecognized entities
                _log(cat, False)
                return CommandResult.failure(f"Application or website '{target}' not found in registry.", cat)

    if "screenshot" in lower:
        cat = "system"
        res = handle_screenshot(command)
        _log(cat, True)
        return CommandResult.success(res, cat)

    if "clipboard" in lower or "copy" in lower or "paste" in lower:
        cat = "system"
        res = handle_clipboard(command)
        _log(cat, True)
        return CommandResult.success(res, cat)
        
    if "add task" in lower or "new task" in lower or "remind me to" in lower or predicted_intent == "task":
        cat = "task"
        res = handle_task(command, _db)
        _log(cat, True)
        return CommandResult.success(res, cat)
        
    if "list tasks" in lower or "show tasks" in lower or "what are my tasks" in lower:
        cat = "task"
        res = handle_task(command, _db)
        _log(cat, True)
        return CommandResult.success(res, cat)
        
    if "complete task" in lower or "finish task" in lower:
        cat = "task"
        res = handle_task(command, _db)
        succ = "not found" not in res.lower() and "specify" not in res.lower()
        _log(cat, succ)
        if succ:
            return CommandResult.success(res, cat)
        return CommandResult.failure(res, cat)
        
    if "delete task" in lower or "remove task" in lower:
        cat = "task"
        res = handle_task(command, _db)
        succ = "not found" not in res.lower() and "specify" not in res.lower()
        _log(cat, succ)
        if succ:
            return CommandResult.success(res, cat)
        return CommandResult.failure(res, cat)
        
    if "what was i doing" in lower or "last task" in lower:
        cat = "task"
        res = handle_task(command, _db)
        _log(cat, True)
        return CommandResult.success(res, cat)

    # --- Memory commands ---
    if _personal_memory:
        cat = "productivity"
        if "remember that" in lower or "remember this" in lower:
            res = _personal_memory.add_memory(command)
            _log(cat, True)
            return CommandResult.success(res, cat)
            
        if "what do you remember" in lower or "list memories" in lower or "list memory" in lower:
            res = _personal_memory.list_memories()
            _log(cat, True)
            return CommandResult.success(res, cat)
            
        if "delete memory" in lower:
            match = re.search(r"delete memory\s*(\d+)", lower)
            if match:
                memory_id = int(match.group(1))
                res = _personal_memory.delete_memory(memory_id)
                succ = "deleted" in res.lower()
                _log(cat, succ)
                if succ:
                    return CommandResult.success(res, cat)
                return CommandResult.failure(res, cat)
            _log(cat, False)
            return CommandResult.failure("Which memory ID should I delete?", cat)

    if lower.strip() in ["confirm", "yes", "proceed"] and _session_memory:
        cat = "ai"
        pending = getattr(_session_memory, "pending_file", None)
        if pending:
            # We had a pending file action requiring confirmation
            filename = pending["filename"]
            content = pending["content"]
            title = pending["title"]
            filepath = pending["filepath"]
            format_ext = pending["format_ext"]

            _session_memory.update(command, "File confirmed.")
            # Clear pending
            _session_memory.pending_file = None

            if format_ext == ".xlsx":
                try:
                    save_as_xlsx(content, filepath, title=title)
                except Exception:
                    save_as_docx(content, filepath.replace(".xlsx", ".docx"), title=title)
                    filename = filename.replace(".xlsx", ".docx")
            elif format_ext == ".docx":
                save_as_docx(content, filepath, title=title)
            elif format_ext == ".txt":
                save_as_text(content, filepath)
            else:
                save_as_code(content, filepath)
                
            msg = f"Action confirmed. {filename} saved on your Desktop."
            _log(cat, True)
            return CommandResult.success(msg, cat)

    ai_triggers = ["draft", "research", "explain", "plan", "notes",
                   "write", "compose", "analyze", "summarize", "describe",
                   "what is", "what are", "how does", "how do",
                   "tell me about", "create notes", "make notes",
                   "look up", "look into", "investigate", "code", "program"]

    # --- Conversational Flow ("more", "save it", "yes") ---
    if lower.strip() in ["yes", "yeah", "yep", "sure", "do it", "please do"]:
        cat = "ai"
        if _session_memory and _session_memory.get_last().get("last_response"):
            last_resp = _session_memory.get_last().get("last_response")
            # Check if Jarvis just asked to create a document
            if "Would you like me to create a full document on this" in last_resp:
                last_cmd = _session_memory.get_last().get("last_command", "")
                # Rewrite command to trigger the document generator
                command = "draft document on " + last_cmd
                lower = command.lower()
                print("[AI] User confirmed document creation.")
                # Fall through to the main AI handler below

    if "more" == lower.strip() or "tell me more" in lower or "explain more" in lower:
        cat = "ai"
        if _session_memory and _session_memory.get_last().get("last_command"):
            last_cmd = _session_memory.get_last().get("last_command")
            # Ensure the last command was an AI question
            if any(t in last_cmd.lower() for t in ai_triggers):
                print("[AI] Generating response (more detail)...")
                memories = _personal_memory._memories if _personal_memory else []
                prompt = _prompt_builder.build("explain", last_cmd, memories, detail_level="long")
                # Tell me more
                result = _ai_engine.generate(prompt)
                
                if _analytics_tracker:
                    _analytics_tracker.log_ai_call(result.get("success", False))

                if not result.get("success", False):
                    err = result.get("error", "AI request failed.")
                    _log(cat, False)
                    return CommandResult.failure(err, cat)
                
                ai_output = result.get("content", "")
                _last_ai_output = ai_output
                _session_memory.update(command, ai_output)
                _log(cat, True)
                return CommandResult.success(ai_output, cat)
        _log(cat, False)
        return CommandResult.failure("I don't have enough context to explain more. Please ask a specific question.", cat)

    if lower.strip() in ["save it", "save that", "create document"]:
        cat = "ai"
        if not _last_ai_output:
            _log(cat, False)
            return CommandResult.failure("There is no recent output to save.", cat)
        
        if not os.path.exists(JARVIS_OUTPUT_DIR):
            os.makedirs(JARVIS_OUTPUT_DIR)
            
        topic = "saved_output"
        if _session_memory and _session_memory.get_last().get("last_command"):
            topic = AIGuard.sanitize_filename(_session_memory.get_last().get("last_command"))
        
        filename = topic + ".docx"
        filepath = os.path.join(JARVIS_OUTPUT_DIR, filename)
        save_as_docx(_last_ai_output, filepath, title=topic.replace("_", " ").title())
        msg = "Content saved as " + filename + " on your Desktop."
        _log(cat, True)
        return CommandResult.success(msg, cat)

    # --- Save last AI output (custom name) ---
    if lower.startswith("save as "):
        cat = "ai"
        filename = command[8:].strip()
        if not filename:
            _log(cat, False)
            return CommandResult.failure("Please specify a filename.", cat)
        # Prevent Path Traversal by extracting just the basename
        filename = os.path.basename(filename)
        if not filename.endswith(".txt"):
            filename += ".txt"
        if not os.path.exists(JARVIS_OUTPUT_DIR):
            os.makedirs(JARVIS_OUTPUT_DIR)
        filepath = os.path.join(JARVIS_OUTPUT_DIR, filename)
        if not _last_ai_output:
            _log(cat, False)
            return CommandResult.failure("No AI output to save.", cat)
        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(_last_ai_output)
            _log(cat, True)
            return CommandResult.success("Saved to " + filepath, cat)
        except Exception as e:
            _log(cat, False)
            return CommandResult.failure("Error saving file: " + str(e), cat)

    # --- AI commands ---
    # Task types that produce documents (auto-save to file)
    _document_tasks = {"draft", "research", "plan", "notes"}
    
    if _ai_engine and (any(trigger in lower for trigger in ai_triggers) or predicted_intent in ["explain", "generate", "analyze", "search"]):
        cat = "ai"
        try:
            task_type = predicted_intent if predicted_intent in ["explain", "generate", "analyze", "search"] else (_ai_router.route(command) if _ai_router else "explain")
            memories = []
            if _personal_memory:
                memories = _personal_memory._memories
            
            # Determine detail level for 'explain'
            detail_level = "short"  # Default to 2-3 sentences max

            prompt = _prompt_builder.build(task_type, command, memories, detail_level) if _prompt_builder else command
            print(f"[AI] Generating response ({task_type})...")
            result = _ai_engine.generate(prompt)

            if _analytics_tracker:
                _analytics_tracker.log_ai_call(result.get("success", False))
            
            if not result.get("success", False):
                err = result.get("error", "AI request failed.")
                _log(cat, False)
                return CommandResult.failure(err, cat)
                
            ai_output = result.get("content", "")
            _last_ai_output = ai_output
            
            if _session_memory:
                _session_memory.update(command, ai_output)

            # Output logic based on target format
            format_ext = _ai_router.get_format(task_type, command) if _ai_router else ".docx"
            
            if task_type in ["draft", "research", "plan", "analyze", "notes", "code"]:
                if not os.path.exists(JARVIS_OUTPUT_DIR):
                    os.makedirs(JARVIS_OUTPUT_DIR)
                
                # Generate base filename
                safe_name = AIGuard.sanitize_filename(lower)
                if not safe_name:
                    safe_name = task_type + "_output"
                title = safe_name.replace("_", " ").title()
                
                filename = safe_name + format_ext
                filepath = os.path.join(JARVIS_OUTPUT_DIR, filename)

                if AIGuard.requires_confirmation(filename):
                    if _session_memory:
                        # Store pending action
                        _session_memory.update(command, "Pending confirmation for " + filename)
                        _session_memory.pending_file = {
                            "filename": filename,
                            "content": ai_output,
                            "title": title,
                            "filepath": filepath,
                            "format_ext": format_ext
                        }
                    msg = f"Safety check: Generating {filename} requires confirmation. Say 'confirm' to proceed."
                    _log(cat, True)
                    return CommandResult.success(msg, cat) # Returns success because it successfully intercepted

                if format_ext == ".xlsx":
                    try:
                        save_as_xlsx(ai_output, filepath, title=title)
                    except Exception:
                        save_as_docx(ai_output, filepath.replace(".xlsx", ".docx"), title=title)
                        filename = filename.replace(".xlsx", ".docx")
                elif format_ext == ".docx":
                    save_as_docx(ai_output, filepath, title=title)
                elif format_ext == ".txt":
                    save_as_text(ai_output, filepath)
                else: # code files (.py, .js, etc)
                    save_as_code(ai_output, filepath)

                _log(cat, True)
                return CommandResult.success(f"Document generated successfully.", cat)
            else:
                # Conversational responses (explain)
                if not AIGuard.should_speak_full_output(ai_output):
                    _log(cat, True)
                    return CommandResult.success("Document generated successfully.", cat)
                _log(cat, True)
                return CommandResult.success(ai_output, cat)
        except Exception as e:
            _log(cat, False)
            return CommandResult.failure("AI processing error: " + str(e), cat)

    cat = "system"
    if not predicted_intent:
        intent, conf = _intent_classifier.classify(command)
        if conf >= 0.7 and intent:
            return _route_single_command(command, bypass_strict_validation=True, predicted_intent=intent)
            
    _log(cat, False)
    return CommandResult.failure("I did not understand the command.", cat)
